import type { IRCheckResult } from "../ir/checker.js";
import type { GapItem, RulebookSignals } from "./types.js";

export interface GapReport {
  gaps: GapItem[];
  summary: {
    errors: number;
    warnings: number;
  };
  notes: string[];
}

export function buildGapReport(
  _irDraft: unknown,
  checkerResult: IRCheckResult,
  extractionDebug: Record<string, unknown>
): GapReport {
  const gaps: GapItem[] = [];

  for (const message of checkerResult.errors) {
    gaps.push({
      filePointer: messageToPointer(message),
      severity: "error",
      message
    });
  }
  for (const message of checkerResult.warnings) {
    gaps.push({
      filePointer: messageToPointer(message),
      severity: "warning",
      message
    });
  }

  const signals = extractSignalsFromDebug(extractionDebug);
  if (!signals.players?.min || !signals.players?.max) {
    gaps.push({
      filePointer: "/meta/playersMin",
      severity: "warning",
      message: "Ambiguous player count in rulebook text.",
      suggestedFix: "Specify exact player count in the rulebook or set meta.playersMin/meta.playersMax manually."
    });
  }
  if (signals.endHints.length === 0) {
    gaps.push({
      filePointer: "/end/kind",
      severity: "warning",
      message: "End condition is ambiguous or missing in extracted signals.",
      suggestedFix: "Describe game end condition explicitly (win/draw/turn limit/score target)."
    });
  }
  if (signals.actionHints.length === 0) {
    gaps.push({
      filePointer: "/actions",
      severity: "warning",
      message: "No clear actions detected from rulebook text.",
      suggestedFix: "Add explicit action descriptions with verbs like place/take/buy."
    });
  }

  for (const unsupported of signals.possibleUnsupportedActionKinds) {
    gaps.push({
      filePointer: "/actions",
      severity: "warning",
      message: `Possible unsupported action signal detected: ${unsupported}`,
      suggestedFix: "Restrict to supported action kinds or extend IR/compiler support."
    });
  }

  const sorted = sortGaps(gaps);
  const summary = {
    errors: sorted.filter((gap) => gap.severity === "error").length,
    warnings: sorted.filter((gap) => gap.severity === "warning").length
  };
  const notes = buildNotes(summary, extractionDebug);

  return {
    gaps: sorted,
    summary,
    notes
  };
}

function messageToPointer(message: string): string {
  const separatorIndex = message.indexOf(":");
  if (separatorIndex <= 0) {
    return "/";
  }
  const path = message.slice(0, separatorIndex).trim();
  if (path === "(root)") {
    return "/";
  }
  return `/${path.split(".").join("/")}`;
}

function sortGaps(gaps: GapItem[]): GapItem[] {
  const unique = new Map<string, GapItem>();
  for (const gap of gaps) {
    const key = `${gap.severity}|${gap.filePointer}|${gap.message}|${gap.suggestedFix ?? ""}`;
    if (!unique.has(key)) {
      unique.set(key, gap);
    }
  }

  return [...unique.values()].sort((a, b) => {
    const severityRank = severityWeight(a.severity) - severityWeight(b.severity);
    if (severityRank !== 0) {
      return severityRank;
    }
    const pointerCmp = a.filePointer.localeCompare(b.filePointer);
    if (pointerCmp !== 0) {
      return pointerCmp;
    }
    return a.message.localeCompare(b.message);
  });
}

function severityWeight(value: GapItem["severity"]): number {
  return value === "error" ? 0 : 1;
}

function buildNotes(summary: { errors: number; warnings: number }, extractionDebug: Record<string, unknown>): string[] {
  const notes: string[] = ["Deterministic gap report generated by rulebook pipeline v0."];
  const recognizer = typeof extractionDebug.selectedRecognizer === "string" ? extractionDebug.selectedRecognizer : "unknown";
  notes.push(`Recognizer: ${recognizer}`);
  notes.push(`Summary: ${summary.errors} error(s), ${summary.warnings} warning(s).`);
  return notes;
}

function extractSignalsFromDebug(extractionDebug: Record<string, unknown>): RulebookSignals {
  const rawSignals = extractionDebug.signals;
  if (!rawSignals || typeof rawSignals !== "object") {
    return {
      setupHints: [],
      turnHints: [],
      actionHints: [],
      endHints: [],
      scoringHints: [],
      keywords: [],
      possibleUnsupportedActionKinds: [],
      confidence: {
        tictactoe: 0,
        miniSplendor: 0,
        connect4: 0,
        nim: 0,
        pig: 0
      }
    };
  }

  const typed = rawSignals as RulebookSignals;
  return {
    players: typed.players,
    setupHints: typed.setupHints ?? [],
    turnHints: typed.turnHints ?? [],
    actionHints: typed.actionHints ?? [],
    endHints: typed.endHints ?? [],
    scoringHints: typed.scoringHints ?? [],
    keywords: typed.keywords ?? [],
    possibleUnsupportedActionKinds: typed.possibleUnsupportedActionKinds ?? [],
    confidence: typed.confidence ?? { tictactoe: 0, miniSplendor: 0, connect4: 0, nim: 0, pig: 0 }
  };
}
